"""adjusted foriegn key

Revision ID: 65e0b09005f1
Revises: 1eda1ec8199f
Create Date: 2023-04-06 14:18:40.123995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e0b09005f1'
down_revision = '1eda1ec8199f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_managers_player_id_players', type_='foreignkey')
        batch_op.drop_column('player_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_player_id_players', type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_teams_player_id_players', 'players', ['player_id'], ['id'])

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_managers_player_id_players', 'players', ['player_id'], ['id'])

    # ### end Alembic commands ###
